comment: false
coverage:
    status:
        project:
            default:
                target: auto
        patch:
            default:
                target: auto
github_checks:
  annotations: false
