cookietemple_version: '1.2.2 # <<COOKIETEMPLE_NO_BUMP>>'
domain: cli
language: python
project_slug: cookietemple
project_slug_no_hyphen: cookietemple
template_version: '1.1.0 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: cookiejar
creator_github_username: Zethson
is_github_repo: true
is_repo_private: false
is_github_orga: true
github_orga: cookiejar
full_name: Lukas Heumos, Philipp Ehmele
email: lukas.heumos@posteo.net
project_name: cookietemple
project_short_description: A cookiecutter based project template creation tool supporting
  several domains and languages with linting and template sync support.
version: 1.2.2
license: Apache2.0
command_line_interface: Click
testing_library: pytest
