from cookietemple.list.list import list_available_templates

"""
This test class is for testing the list subcommand:

Syntax: cookietemple list
"""


def test_non_empty_output(capfd):
    """
    Verifies that the list command does indeed have content

    :param capfd: pytest fixture -> capfd: Capture, as text, output to file descriptors 1 and 2.
    """
    # Capture stdout
    list_available_templates()
    out, err = capfd.readouterr()

    assert len(out) > 20


def test_header(capfd):
    """
    Verifies that the list command does have the following header
    Name    Handle    Short Description    Available Libraries    Version

    :param capfd: pytest fixture -> capfd: Capture, as text, output to file descriptors 1 and 2.
    """
    expected_headers = ['Name', 'Handle', 'Short', 'Description', 'Available', 'Libraries', 'Version']

    # Capture stdout
    list_available_templates()
    out, err = capfd.readouterr()
    # We skip the COOKIETEMPLE autogenerated lines (0-2)
    header = out.split('\n')[3].split()

    assert header == expected_headers
