name: Run {{ cookiecutter.project_slug }} Tox Test Suite

on: [push, pull_request]

jobs:
  test:
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: {% raw %}${{ matrix.python }}{% endraw %}

      - name: Install Tox
        run: pip install tox

      - name: Run Tox
        run: tox -e py  # Run tox using the version of Python in `PATH`
