name: cookietemple lint

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              name: Check out source-code repository

            - name: Setup Python
              uses: actions/setup-python@v3
              with:
                  python-version: 3.9

            - name: Install cookietemple
              run: pip install cookietemple==1.3.3

            - name: Run cookietemple lint
              run: cookietemple lint . --skip-external
