name: cookietemple lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9

      - name: Install cookietemple
        run: |
          pip install cookietemple

      - name: Run cookietemple lint
        run: |
          cookietemple lint . --skip-external
